### ISSUE TITLE
[Bug]: can't compile successfully on ubuntu-22.04

### ISSUE THREAD

**Issue by cessory** [cubefs/cubefs#1925]
**Describe the bug**
execute make server to compile CubeFS and report an error

```shell
build cfs-server   # github.com/tecbot/gorocksdb
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/librocksdb.a(format.o): in function `rocksdb::LZ4_Uncompress(char const*, unsigned long, int*, unsigned int, rocksdb::Slice const&)':
/go/src/cubefs/build/out/rocksdb/./util/compression.h:617: undefined reference to `LZ4_createStreamDecode'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:622: undefined reference to `LZ4_decompress_safe_continue'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:625: undefined reference to `LZ4_freeStreamDecode'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:617: undefined reference to `LZ4_createStreamDecode'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:622: undefined reference to `LZ4_decompress_safe_continue'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:625: undefined reference to `LZ4_freeStreamDecode'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:619: undefined reference to `LZ4_setStreamDecode'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:619: undefined reference to `LZ4_setStreamDecode'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/librocksdb.a(block_based_table_builder.o): in function `rocksdb::LZ4HC_Compress(rocksdb::CompressionOptions const&, unsigned int, char const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, rocksdb::Slice const&)':
/go/src/cubefs/build/out/rocksdb/./util/compression.h:671: undefined reference to `LZ4_compressBound'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:676: undefined reference to `LZ4_createStreamHC'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:677: undefined reference to `LZ4_resetStreamHC'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:681: undefined reference to `LZ4_loadDictHC'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:686: undefined reference to `LZ4_compress_HC_continue'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:693: undefined reference to `LZ4_freeStreamHC'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/librocksdb.a(block_based_table_builder.o): in function `rocksdb::LZ4_Compress(rocksdb::CompressionOptions const&, unsigned int, char const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, rocksdb::Slice)':
/go/src/cubefs/build/out/rocksdb/./util/compression.h:552: undefined reference to `LZ4_compressBound'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:557: undefined reference to `LZ4_createStream'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:563: undefined reference to `LZ4_compress_fast_continue'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:571: undefined reference to `LZ4_freeStream'
/usr/bin/ld: /go/src/cubefs/build/out/rocksdb/./util/compression.h:559: undefined reference to `LZ4_loadDict'
```

**Environment**
ubuntu 22.04 gcc11
liblz4 is already installed on the system
```shell
-rw-r--r-- 1 root root 230100 Apr 18 14:41 /usr/local/lib/liblz4.a
lrwxrwxrwx 1 root root     15 Apr 18 14:41 /usr/local/lib/liblz4.so -> liblz4.so.1.9.3
lrwxrwxrwx 1 root root     15 Apr 18 14:41 /usr/local/lib/liblz4.so.1 -> liblz4.so.1.9.3
-rwxr-xr-x 1 root root 207984 Apr 18 14:41 /usr/local/lib/liblz4.so.1.9.3
```

**Comment by leonrayang** [comment]
@cessory please show your command.Does "make server" worked,thank you.

**Comment by lizonglingo** [comment]
I also failed to compile with Ubuntu-22.04. The problem appears to be with the compilation relief for rocksdb. The command and output are as follows:
```shell
root@cubefs-verify0:/work-place/cubefs/cubefs$ make build
db/db_impl_compaction_flush.cc: In member function ‘void rocksdb::DBImpl::NotifyOnCompactionCompleted(rocksdb::ColumnFamilyData*, rocksdb::Compaction*, const rocksdb::Status&, const rocksdb::CompactionJobStats&, int)’:
db/db_impl_compaction_flush.cc:696:21: error: loop variable ‘newf’ creates a copy from type ‘const std::pair<int, rocksdb::FileMetaData>’ [-Werror=range-loop-construct]
  696 |     for (const auto newf : c->edit()->GetNewFiles()) {
      |                     ^~~~
db/db_impl_compaction_flush.cc:696:21: note: use reference type to prevent copying
  696 |     for (const auto newf : c->edit()->GetNewFiles()) {
...
make[1]: Leaving directory '/work-place/cubefs/cubefs/build/out/rocksdb'
build rocksdb failed
make: *** [Makefile:60: build/bin/cfs-server] Error 1
```
